apiVersion: v1
kind: Template
labels:
  template: gsa-comet-agency-ui
metadata:
  annotations:
    description: Comet Front End App template for JWS applications built using a Jenkins Pipeline
    iconClass: icon-tomcat
    tags: nodejs,angular
    version: 1.2.0
  name: gsa-comet-agency-ui
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.insecureRepository: "true" # Allow to pull image from unsecured registry
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    dockerImageRepository: ${DOCKER_REGISTRY}/${APPLICATION_NAME}
    tags:
    - from:
        kind: DockerImage
        name: ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${APPLICATION_VERSION}
      importPolicy:
        insecure: true
      name: ${APPLICATION_VERSION}
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      # type: Recreate
      # https://docs.openshift.com/container-platform/3.9/dev_guide/deployments/deployment_strategies.html
      type: Rolling
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: API_KEY
            value: ${API_KEY}
          - name: API_URL
            value: ${API_URL}
          - name: ENVIRONMENT
            value: ${ENVIRONMENT}
          - name: OKTA_BASE
            value: ${OKTA_BASE}
          - name: OKTA_ISSUER
            value: ${OKTA_ISSUER}
          - name: OKTA_CLIENT_ID
            value: ${OKTA_CLIENT_ID}
          - name: OKTA_REDIRECT
            value: ${OKTA_REDIRECT}
          - name: AGENCY_API
            value: ${API_URL}
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        terminationGracePeriodSeconds: 60
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${APPLICATION_VERSION}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: jws-app
- description: The version of the application.
  name: APPLICATION_VERSION
  value: "latest"
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: Type of the environment where the app would run
  name: ENVIRONMENT
  required: true
- description: API Umbrella Host
  name: API_URL
  required: true
- description: API Umbrella Key
  name: API_KEY
  required: true
- description: Docker registry to push the image
  name: DOCKER_REGISTRY
  value: "nexus-registry-comet.reisystems.io/repository/docker"
- description: 'OKTA Issuer'
  name: OKTA_ISSUER
  required: true
- description: 'OKTA Client ID'
  name: OKTA_CLIENT_ID
  required: true
- description: 'OKTA Redirect'
  name: OKTA_REDIRECT
  required: true
- description: 'OKTA BASE URL'
  name: OKTA_BASE
  required: true
